In [1]:
import pandas as pd
import pandas as pd
import calendar 
from datetime import date, datetime, timedelta
import os


weather_data_2016 = pd.read_csv("/Users/daniel/projects/Python/anomaly_detection/dataset/hourly_weather_2016.csv", thousands=',')
weather_data_2017 = pd.read_csv("/Users/daniel/projects/Python/anomaly_detection/dataset/hourly_weather_2017.csv", thousands=',')
weather_data_2018 = pd.read_csv("/Users/daniel/projects/Python/anomaly_detection/dataset/hourly_weather_2018.csv", thousands=',')
weather_data_2019 = pd.read_csv("/Users/daniel/projects/Python/anomaly_detection/dataset/hourly_weather_2019.csv", thousands=',')

weather_data = pd.concat([weather_data_2016, weather_data_2017, weather_data_2018, weather_data_2019])
weather_data.shape

(46001, 11)

In [2]:
weather_data.head()

,Time,Temperature,Dew Point,Humidity,Wind Speed,Wind Gust,Pressure,Precipitation,Wind,Condition,Date
0,7:30 AM,-1,-3,86,9,0,976.19,0.0,WSW,Cloudy,2016-1-1
1,7:56 AM,-1,-3,86,9,0,976.19,0.0,WSW,Cloudy,2016-1-1
2,8:56 AM,-1,-3,86,11,0,976.19,0.0,WSW,Cloudy,2016-1-1
3,9:56 AM,-1,-2,93,15,0,976.19,0.0,WSW,Cloudy,2016-1-1
4,10:56 AM,-1,-2,93,17,0,976.19,0.0,WSW,Cloudy,2016-1-1

In [3]:
weather_data.to_csv ("/Users/daniel/projects/Python/anomaly_detection/dataset/weather_data.csv")

In [4]:
weather_data_1 = pd.read_csv("/Users/daniel/projects/Python/anomaly_detection/dataset/weather_data.csv", thousands=',')

In [5]:
weather_data_1.head()

,Unnamed: 0,Time,Temperature,Dew Point,Humidity,Wind Speed,Wind Gust,Pressure,Precipitation,Wind,Condition,Date
0,0,7:30 AM,-1,-3,86,9,0,976.19,0.0,WSW,Cloudy,2016-1-1
1,1,7:56 AM,-1,-3,86,9,0,976.19,0.0,WSW,Cloudy,2016-1-1
2,2,8:56 AM,-1,-3,86,11,0,976.19,0.0,WSW,Cloudy,2016-1-1
3,3,9:56 AM,-1,-2,93,15,0,976.19,0.0,WSW,Cloudy,2016-1-1
4,4,10:56 AM,-1,-2,93,17,0,976.19,0.0,WSW,Cloudy,2016-1-1